### ISSUE TITLE
ThermalMonitor segfaults when it is closed

### ISSUE THREAD

**Issue by ColinIanKing** [01org/thermal_daemon#91]
Building on Ubuntu 16.10 Yakkety; exiting ThermalMonitor by closing the window trips a SEGV.

gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc-5.real
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-4ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-4ubuntu1) 

Program received signal SIGSEGV, Segmentation fault.
0x0000000200000001 in ?? ()
(gdb) where
#0  0x0000000200000001 in ?? ()
#1  0x000055555556b8ee in MainWindow::~MainWindow (this=0x7fffffffe120, 
    __in_chrg=<optimised out>) at mainwindow.cpp:118
#2  0x00005555555692c2 in main (argc=1, argv=<optimised out>) at main.cpp:55

**Comment by spandruvada** [comment]
I tried on Ubuntu 16.04 and not able to reproduce this crash. Is is something specific to 16.10?

**Comment by ColinIanKing** [comment]
I'm still trying to corner this; meanwhile here is the current state of ThermalMonitor when one exits, showing that this is a heap re-use issue going on somewhere:

sudo valgrind --track-fds=yes  --malloc-fill=0xaa ./ThermalMonitor 
==11462== Memcheck, a memory error detector
==11462== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==11462== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==11462== Command: ./ThermalMonitor
==11462== 
==11463== Warning: invalid file descriptor 1024 in syscall close()
==11463== Warning: invalid file descriptor 1025 in syscall close()
==11463== Warning: invalid file descriptor 1026 in syscall close()
==11463== Warning: invalid file descriptor 1027 in syscall close()
==11463==    Use --log-fd=<number> to select an alternative log fd.
==11463== Warning: invalid file descriptor 1028 in syscall close()
==11463== Warning: invalid file descriptor 1029 in syscall close()
==11462== Invalid read of size 8
==11462==    at 0x11F948: MainWindow::~MainWindow() (mainwindow.cpp:118)
==11462==    by 0x11D321: main (main.cpp:55)
==11462==  Address 0xebf5550 is 0 bytes inside a block of size 32 free'd
==11462==    at 0x4C2F24B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11462==    by 0x52D81D0: QWidget::~QWidget() (in /usr/lib/x86_64-linux-gnu/libQtGui.so.4.8.7)
==11462==    by 0x52D8668: QWidget::~QWidget() (in /usr/lib/x86_64-linux-gnu/libQtGui.so.4.8.7)
==11462==    by 0x11F93B: MainWindow::~MainWindow() (mainwindow.cpp:117)
==11462==    by 0x11D321: main (main.cpp:55)
==11462==  Block was alloc'd at
==11462==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11462==    by 0x120D0C: MainWindow::MainWindow(QWidget*) (mainwindow.cpp:103)
==11462==    by 0x11D304: main (main.cpp:55)

**Comment by sandsmark** [comment]
it tried to delete one of the QObjects...

one of the commits here fixes it: https://github.com/01org/thermal_daemon/pull/96

**Comment by spandruvada** [comment]
On Wed, 2016-07-20 at 14:28 -0700, martin wrote:
> it tried to delete one of the QObjects...
> one of the commits here fixes it: #96
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

Thanks Martin. I am travelling and on vacation. So will check your
fixes.
